scp_control_node:
  ros__parameters:
    config_on_start:
      agent_name: "agent_0"
      control_frequency: 50.0
      max_velocity: 0.3
      max_angular_velocity: 0.39269908169872415480783042290994
    config_on_running:
      P: 0.1
      I: 0.0
      D: 0.0

