/uvs_mapserver:
  ros__parameters:
    world_name: "jxl3028"
/uve_simoptitrack:
  ros__parameters:
    sim_opt_name: ["uv05", "c1", "c2", "c3", "c4"]
    sim_opt_pose: [
      0.324, -3.24, 0.0,
      -2.0, -0.864, 0.0,
      -0.258, 0.249, 0.0, 
      1.52, -0.316, 0.0,
      -0.274, 2.59, 0.0
      # 0.324, -3.24, 0.0,
      # 1.52, -0.316, 0.0,
      # 1.52, -0.316, 0.0,
      # 1.52, -0.316, 0.0,
      # 1.52, -0.316, 0.0
    ]
/uve_plan:
  ros__parameters:
    free_graph_path: /config/free.json
    carry_graph_path: /config/carry.json
    max_thread: 4
    freespace:
      max_v: 0.3
      max_w: 0.78539816339744830961566084582
      # max_w:  0.5
      step_v: 2
      step_w: 2
      dt: 0.5
    carryspace:
      max_v: 0.3
      max_w: 0.78539816339744830961566084582
      # max_w:  0.5
      step_v: 2
      step_w: 2
      dt: 0.5
    checkpoints: [
      1.0, 0.0, 0.0,
      -1.0, 0.0, 0.0
    ]
/uve_control:
  ros__parameters:
    uve_control:
      mpc:
        horizon:  10
        dt: 0.1
        Q:  [
          10.0, 0.0, 0.0,
          0.0, 10.0, 0.0,
          0.0, 0.0, 0.1
        ]
        R:  [
          1.0, 0.0,
          0.0, 0.01
        ]
        Qf: [
          10.0, 0.0, 0.0,
          0.0, 10.0, 0.0,
          0.0, 0.0, 0.5
        ]
        wheelWidth: 0.238
        maxWheelSpeed:  0.3
      arm:
        arm_off:  3855
        arm_on:  3080
        base_off:  308
        base_on:  840